# Generated by Django 5.2.6 on 2025-09-07 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('perlengkapanUtama', 'Perlengkapan Utama'), ('bolanAksesrori', 'Bola dan Aksesoris'), ('peralatanLatihan', 'Peralatan Latihan'), ('perlatanWasit', 'Peralatan Wasit'), ('sportCare', 'Sport Care'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('hotDeals', 'Hot Deals')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('brand', models.CharField()),
                ('items_viewer', models.PositiveIntegerField(default=0)),
                ('size', models.CharField()),
            ],
        ),
    ]
