# Generated by Django 5.2.6 on 2025-09-14 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='items_viewer',
            new_name='product_viewer',
        ),
        migrations.AddField(
            model_name='product',
            name='launch_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
