# Generated by Django 5.2.6 on 2025-10-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('perlengkapanUtama', 'Perlengkapan Utama'), ('bolanAksesoris', 'Bola dan Aksesoris'), ('peralatanLatihan', 'Peralatan Latihan'), ('perlatanWasit', 'Peralatan Wasit'), ('sportCare', 'Sport Care'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('hotDeals', 'Hot Deals')], default='update', max_length=20),
        ),
    ]
